version: '3'

services:
  web:
    build:
      context: .
    image: shipchoice:${SHIPCHOICE_TAG:-latest}
    command: bash -c 'dockerize -wait tcp://postgres:5432 -timeout 1m && /app/bin/start_server foreground'
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
    #   interval: 20s
    #   timeout: 10s
    #   retries: 5
    environment:
      # - HOST=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=shipchoice_db
      - DB_HOSTNAME=postgres
      - SECRET_KEY_BASE=foobarbaz
    depends_on:
      - postgres
    networks:
      - main

  postgres:
    image: postgres:11
    ports:
      - 5432
    volumes:
      - ./data:/var/lib/postgresql/data:cached
    environment:
      - POSTGRES_DB=shipchoice_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - main

networks:
  main:

volumes:
  postgres:
