apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipchoice-deployment
spec:
  selector:
    matchLabels:
      app: shipchoice
  replicas: 1
  template:
    metadata:
      labels:
        app: shipchoice
    spec:
      containers:
        - name: shipchoice
          image: gcr.io/shipchoice-20180716/shipchoice:0.0.9
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: HOST
              value: "shypchoice.com"
            - name: DB_NAME
              value: "shipchoice_db_prod"
            - name: DB_HOSTNAME
              value: postgresql
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: shipchoice-postgres-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shipchoice-postgres-credentials
                  key: password
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: shipchoice-credentials
                  key: secret-key-base
            - name: APITEL_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: shipchoice-apitel-credentials
                  key: apitel-sender-id
            - name: APITEL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shipchoice-apitel-credentials
                  key: apitel-api-key
            - name: APITEL_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: shipchoice-apitel-credentials
                  key: apitel-api-secret
            - name: BITLY_GROUP_GUID
              valueFrom:
                secretKeyRef:
                  name: shipchoice-bitly-credentials
                  key: bitly-group-guid
            - name: BITLY_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: shipchoice-bitly-credentials
                  key: bitly-access-token
