apiVersion: v1
kind: Service
metadata:
  name: shipchoice-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: shipchoice
  type: LoadBalancer
